#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
newAttribute=new Attribute
longitudeMin=Longitude min
classPlural=D\u00E9versoirs
photos=Photos
seuil=Seuil
borne_fin_distance=Distance (borne fin)
date_fin=Date de fin
gestions=Gestionnaires
geometryMode=geometry Mode
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
positionDebut=Position de d\u00E9but
typeSecurite=Type de s\u00E9curit\u00E9
photo=Photo
author=Auteur
prDebut=PR de d\u00E9but
borne_debut_aval=En amont de la borne de d\u00E9but
class=D\u00E9versoir
borneFinId=Borne de fin
libelle=Libell\u00E9
geometry=G\u00E9om\u00E9trie
conventionIds=Conventions
dateMaj=Mise \u00E0 jour
latitudeMin=Latitude min
designation=D\u00E9signation
classAbrege=Dv
fonctionId=Fonction
approximatePositionFin=Approximation de la position Fin
sourceId=Source
borne_debut_distance=Distance (borne d\u00E9but)
longitudeMax=Longitude max
systemeRepId=Syst\u00E8me de rep\u00E9rage
approximatePositionDebut=Approximation de la position Debut
linearId=Tron\u00E7on
borne_fin_aval=En amont de la borne de fin
fusible=Fusible
prFin=PR de fin
gardes=Gardiens
valid=Valid\u00E9
proprietes=Propri\u00E9taires
fosse=Fosse
editedGeoCoordinate=Coordonn\u00E9es Geo \u00E9dit\u00E9es
crsName=CRS Name
coteId=C\u00F4t\u00E9
date_debut=Date de d\u00E9but
latitudeMax=Latitude max
raccordementId=Raccordement \u00E0 la digue
positionFin=Position de fin
commentaire=Commentaire
borneDebutId=Borne de d\u00E9but
coteSurverse=Cote de d\u00E9but de surverse
typeAlimentation=Type d'alimentation
contactStructure=Contact
organismeStructure=Organisme
