#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
positionFin=Position de fin
positionDebut=Position de d\u00E9but
approximatePositionFin=Approximation de la position Fin
borne_debut_aval=En amont de la borne de d\u00E9but
borneFinId=Borne de fin
newAttribute=new Attribute
author=Auteur
prFin=PR de fin
borne_fin_aval=En amont de la borne de fin
geometry=geometry
systemeRepId=Syst\u00E8me de rep\u00E9rage
crsName=CRS Name
prDebut=PR de d\u00E9but
typeContact=type Contact
geometryMode=Geometry Mode
borneDebutId=Borne de d\u00E9but
longitudeMin=Longitude min
classAbrege=GT
longitudeMax=Longitude max
class=P\u00E9riode de gardiennage (tron\u00E7on)
editedGeoCoordinate=Coordonn\u00E9es Geo \u00E9dit\u00E9es
valid=Valid\u00E9
linearId=Tron\u00E7on
contactId=Contact
date_fin=Date de fin
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
latitudeMin=Latitude min
designation=D\u00E9signation
borne_debut_distance=Distance (borne d\u00E9but)
date_debut=Date de d\u00E9but
dateMaj=Mise \u00E0 jour
latitudeMax=Latitude max
borne_fin_distance=Distance (borne fin)
approximatePositionDebut=Approximation de la position Debut
classPlural=P\u00E9riode de gardiennage (tron\u00E7on)s
