#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
newAttribute=new Attribute
longitudeMin=Longitude min
classPlural=Mont\u00E9es des eaux
photos=Photos
borne_fin_distance=Distance (borne fin)
date_fin=Date de fin
gestions=Gestionnaires
troncon=Tron\u00E7on
geometryMode=geometry Mode
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
positionDebut=Position de d\u00E9but
photo=Photo
articleJournal=Article de journal
author=Auteur
prDebut=PR de d\u00E9but
borne_debut_aval=En amont de la borne de d\u00E9but
class=Mont\u00E9e des eaux
borneFinId=Borne de fin
evenementHydrauliqueId=\u00C9v\u00E9nement hydraulique
geometry=G\u00E9om\u00E9trie
conventionIds=Conventions
dateMaj=Mise \u00E0 jour
latitudeMin=Latitude min
designation=D\u00E9signation
classAbrege=ME
approximatePositionFin=Approximation de la position Fin
sourceId=Source
borne_debut_distance=Distance (borne d\u00E9but)
longitudeMax=Longitude max
systemeRepId=Syst\u00E8me de rep\u00E9rage
approximatePositionDebut=Approximation de la position Debut
linearId=Tron\u00E7on
echelleLimnimetriqueId=\u00C9chelle limnimetrique
borne_fin_aval=En amont de la borne de fin
mesures=Mesures
prFin=PR de fin
gardes=Gardiens
valid=Valid\u00E9
proprietes=Propri\u00E9taires
crsName=CRS Name
editedGeoCoordinate=Coordonn\u00E9es Geo \u00E9dit\u00E9es
coteId=C\u00F4t\u00E9
articleIds=Article
date_debut=Date de d\u00E9but
echelleLimnimetrique=\u00C9chelle limnim\u00E9trique
latitudeMax=Latitude max
positionFin=Position de fin
borneDebutId=Borne de d\u00E9but
commentaire=Commentaire
contactStructure=Contact
organismeStructure=Gestionnaires
