#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
newAttribute=new Attribute
longitudeMin=longitude Min
classPlural=ObjetMesures
photos=photos
borne_fin_distance=borne fin distance
date_fin=date fin
geometryMode=geometry Mode
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
positionDebut=Position Debut
author=Auteur
prDebut=pr Debut
borne_debut_aval=En amont de la borne de d\u00E9but
class=ObjetMesure
borneFinId=Borne fin
evenementHydrauliqueId=Ev\u00E9nement Hydraulique
geometry=geometry
dateMaj=date Maj
latitudeMin=latitude Min
designation=designation
classAbrege=OM
approximatePositionFin=Approximation de la position Fin
borne_debut_distance=borne debut distance
longitudeMax=longitude Max
systemeRepId=Syst\u00E8me de Rep\u00E9rage
approximatePositionDebut=Position Debut approch\u00E9e
linearId=linear Id
borne_fin_aval=En amont de la borne de fin
prFin=pr Fin
valid=valid
editedGeoCoordinate=Coordinonn\u00E9es g\u00E9o \u00E9dit\u00E9es
crsName=CRS Name
articleIds=Articles
date_debut=date debut
latitudeMax=latitude Max
positionFin=Position Fin
borneDebutId=Borne Debut
commentaire=commentaire
