#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
nomFichierPlanEnsemble=Fichier de plan d'ensemble
newAttribute=new Attribute
longitudeMin=Longitude min
classPlural=Profil en longs
pointsLeveDZ=Pr/Z
chemin=Chemin vers le fichier
borne_fin_distance=Distance (borne fin)
origineProfilLongId=Origine
geometryMode=geometry Mode
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
document=Document
positionDebut=Position de d\u00E9but
typeSystemesReleveId=Type de syst\u00E8me de relev\u00E9
author=Auteur
prDebut=PR de d\u00E9but
borne_debut_aval=En amont de la borne de d\u00E9but
dateLeve=Date de lev\u00E9
systemeRepDzId=Syst\u00E8me de rep\u00E9rage des points Pr/Z
class=Profil en long
parametresHydrauliques=Param\u00E8tres hydrauliques
borneFinId=Borne de fin
positionProfilLongSurDigueId=Position sur digue
libelle=Libell\u00E9
geometry=G\u00E9om\u00E9trie
dateMaj=Mise \u00E0 jour
referencePapier=R\u00E9f\u00E9rence papier
latitudeMin=Latitude min
designation=D\u00E9signation
classAbrege=PL
approximatePositionFin=Approximation de la position Fin
nomFichierCoupeImage=Fichier de coupe image
organismeCreateurId=Organisme cr\u00E9ateur
borne_debut_distance=Distance (borne d\u00E9but)
longitudeMax=Longitude max
systemeRepId=Syst\u00E8me de rep\u00E9rage
borne_fin_aval=En amont de la borne de fin
linearId=Tron\u00E7on
approximatePositionDebut=Approximation de la position Debut
rapportEtudeId=Rapport d'\u00E9tude
prFin=PR de fin
valid=Valid\u00E9
pointsLeveXYZ=XYZ
crsName=CRS Name
editedGeoCoordinate=Coordonn\u00E9es Geo \u00E9dit\u00E9es
leveePoints=Points de lev\u00E9
coteId=C\u00F4t\u00E9
profilLongEvenementHydraulique=Param\u00E8tres hydrauliques
latitudeMax=Latitude max
positionId=Position
positionFin=Position de fin
commentaire=Commentaire
borneDebutId=Borne de d\u00E9but
referenceCalque=R\u00E9f\u00E9rence calque
