#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
newAttribute=new Attribute
longitudeMin=Longitude min
classPlural=R\u00E9seau de t\u00E9l\u00E9communication et \u00E9nergies
photos=Photos
borne_fin_distance=Distance (borne fin)
date_fin=Date de fin
gestions=Gestionnaires
troncon=Tron\u00E7on
geometryMode=geometry Mode
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
securiteId=S\u00E9curit\u00E9
positionDebut=Position de d\u00E9but
photo=Photo
observations=Observations
desordreIds=D\u00E9sordres
author=Auteur
prDebut=PR de d\u00E9but
borne_debut_aval=En amont de la borne de d\u00E9but
class=R\u00E9seau de t\u00E9l\u00E9communication et \u00E9nergie
borneFinId=Borne de fin
libelle=Libell\u00E9
geometry=G\u00E9om\u00E9trie
conventionIds=Conventions
dateMaj=Mise \u00E0 jour
dimensionHorizontale=Dimension horizontale (mm)
latitudeMin=Latitude min
typeReseauTelecomEnergieId=Type de r\u00E9seau
designation=D\u00E9signation
classAbrege=RTE
approximatePositionFin=Approximation de la position Fin
sourceId=Source
borne_debut_distance=Distance (borne d\u00E9but)
longitudeMax=Longitude max
systemeRepId=Syst\u00E8me de rep\u00E9rage
approximatePositionDebut=Approximation de la position Debut
linearId=Tron\u00E7on
borne_fin_aval=En amont de la borne de fin
prFin=PR de fin
gardes=Gardiens
valid=Valid\u00E9
ouvrageTelecomEnergieIds=Ouvrage t\u00E9l\u00E9com ou \u00E9nergie
proprietes=Propri\u00E9taires
editedGeoCoordinate=Coordonn\u00E9es Geo \u00E9dit\u00E9es
crsName=CRS Name
coteId=C\u00F4t\u00E9
date_debut=Date de d\u00E9but
hauteur=Hauteur a\u00E9rienne (m)
dimensionVerticale=Dimension verticale/diam\u00E8tre (mm)
prestationIds=Prestations
latitudeMax=Latitude max
positionFin=Position de fin
positionId=Position
commentaire=Commentaire
borneDebutId=Borne de d\u00E9but
implantationId=Implantation
organismeStructure=Gestionnaires
contactStructure=Contact
