#Added 1 on last update.
#Wed Jan 28 17:14:30 CET 2026
epaisseurSommet=\u00C9paisseur sommet (m)
newAttribute=new Attribute
longitudeMin=Longitude min
classPlural=Talus de digues
photos=Photos
borne_fin_distance=Distance (borne fin)
date_fin=Date de fin
gestions=Gestionnaires
troncon=Tron\u00E7on
numCouche=N\u00B0 couche
natureHautId=Nature du haut
geometryMode=geometry Mode
lastUpdateAuthor=Auteur de la derni\u00E8re mise \u00E0 jour
positionDebut=Position de d\u00E9but
fonctionBasId=Fonction du bas
photo=Photo
author=Auteur
prDebut=PR de d\u00E9but
borne_debut_aval=En amont de la borne de d\u00E9but
class=Talus de digue
materiauBasId=Mat\u00E9riau du bas
borneFinId=Borne de fin
geometry=G\u00E9om\u00E9trie
conventionIds=Conventions
dateMaj=Mise \u00E0 jour
latitudeMin=Latitude min
designation=D\u00E9signation
classAbrege=TD
approximatePositionFin=Approximation de la position Fin
sourceId=Source
borne_debut_distance=Distance (borne d\u00E9but)
longitudeMax=Longitude max
systemeRepId=Syst\u00E8me de rep\u00E9rage
approximatePositionDebut=Approximation de la position Debut
linearId=Tron\u00E7on
borne_fin_aval=En amont de la borne de fin
prFin=PR de fin
longueurRampantHaut=Longueur rampant haut (m)
gardes=Gardiens
valid=Valid\u00E9
longueurRampantBas=Longueur rampant bas (m)
materiauHautId=Mat\u00E9riau du haut
natureBasId=Nature du bas
proprietes=Propri\u00E9taires
editedGeoCoordinate=Coordonn\u00E9es Geo \u00E9dit\u00E9es
crsName=CRS Name
coteId=C\u00F4t\u00E9
date_debut=Date de d\u00E9but
fonctionHautId=Fonction du haut
latitudeMax=Latitude max
positionFin=Position de fin
positionId=Position
borneDebutId=Borne de d\u00E9but
commentaire=Commentaire
organismeStructure=Gestionnaires
contactStructure=Contact
penteInterieure=Pente int\u00E9rieure (%)
